# Generated by Django 4.1.3 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment',
            field=models.CharField(choices=[('COD', 'COD(CASH ON DELIVERY)'), ('PAID', 'PAID')], default='PAID', max_length=50),
        ),
    ]
